### ISSUE TITLE
Chart tooltip not bound to container?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/crow#128]
@stijnvanhoey reported the chart tooltip appearing outside the container of the chart:

> It is just blinking once (unfortunately no mouse on the screenshot), but you can see it yourself if you are with your mouse inside the graph domain and move outside of it (actually this happens for me in any of the four directions). It also happens for this particular data selection when I move from 15:00 CET to the right (passing the no data section I assume):

![image](https://user-images.githubusercontent.com/600993/108967624-0c594300-7680-11eb-8741-e7f334ee68c3.png)

**Comment by peterdesmet** [comment]
@stijnvanhoey I see it too in Chrome, but I was wondering: does the tooltip stay on your screen after leaving the chart? Mine just blinks out of existence, probably because it takes a little bit of time to set these values:

https://github.com/inbo/crow/blob/72c342a0ae6d112b0839510a705cf8fb35e4137c/src/components/VPIChart.vue#L527-L530

**Comment by niconoe** [comment]
I saw that before, if I remember correctly that part of the code was a bit tricky to make work properly (Vue/D3/Bootstrap interactions, on top of advanced CSS).

You're probably right @peterdesmet: for performance reasons, Vue events don't happen immediately (they're stored in a queue, processed at a regular interval). So that might be a symptom of this. I'll look in more details and hopefully find a reasonably simple workaround!

**Comment by stijnvanhoey** [comment]
> blinks out of existence, probably because it takes a little bit of time to set these values:

Indeed, this is just _flashing_ shortly.

**Comment by niconoe** [comment]
I spend some time on this, tried many things (sometimes ugly) and couldn't totally get rid of it. I implemented a solution that appears to make it a bit shorter and therefore less visible. I can revisit later, but I guess it isn't the higher priority du to launch proximity.

**Comment by peterdesmet** [comment]
@niconoe I explored it a little too. I think it is caused because we `v-show: false` the `circle`, which is the target/anchor point of the popover. As a result, the popover does not have an anchor point for a couple of milliseconds, meaning it defaults to the top right of the window.

**Comment by peterdesmet** [comment]
You can see the effect by hardcoding the following line to `true`, but then the circle is always visible which isn't good either:

https://github.com/inbo/crow/blob/9fca50897bcd4584ed508b292e238ce7491d36fe/src/components/VPIChart.vue#L68

Too bad we can't use `:show.sync="tooltipVisible"` on that element

**Comment by peterdesmet** [comment]
This issue still occurs, but I would say it's a minor nuisance.
